services:
  web:
    image: product-card-service/web:latest
    container_name: web
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - product_cars_service_net
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "fitcha"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 20s
      timeout: 5s
      retries: 10
    networks:
      - product_cars_service_net
  card-service:
    image: product-card-service/card-service:latest
    depends_on:
      - postgres
      - web
    ports:
      - "8080:8080"
    networks:
      - product_cars_service_net

networks:
  product_cars_service_net:
